name: 'CI'
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
jobs:
  code-quality: 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        arguments: [ '--ide,QDJVM-EAP,--baseline,qodana.sarif.json' ]
        include:
          - os: ubuntu-latest
            arguments: '--linter,jetbrains/qodana-jvm:latest,--baseline,qodana.sarif.json'
    permissions:
      checks: write
      pull-requests: write
      actions: read
      contents: write
      security-events: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: JetBrains/qodana-action@main
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
          QD_PRODUCT_INTERNAL_FEED: "https://data.services.jetbrains.com/products"
        with:
          use-nightly: true
          pr-mode: false
          args: ${{ matrix.arguments }}
  
